---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    # mappings will be provided via --extra-vars
  tasks:
    - name: Print received mappings (raw)
      debug:
        var: mappings

    - name: Print each service mapping with extracted tag
      debug:
        msg: "{{ item.key }} -> image={{ item.value }} ; tag={{ (item.value | split(':') | last) }}"
      loop: "{{ mappings | dict2items }}"

    - name: Simulate work and emit progress 1..100
      shell: |
        for i in $(seq 1 100); do
          echo "PROGRESS:${i}"
          sleep 0.05
        done
      args:
        executable: /bin/bash

    - name: Final message
      debug:
        msg: "Simulation complete"
